# Generated by Django 4.1.6 on 2023-02-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_github',
            field=models.URLField(blank=True),
        ),
    ]
